<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>COVID19</title>

<script src="site_libs/header-attrs-2.10/header-attrs.js"></script>
<script src="site_libs/jquery-3.5.1/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="site_libs/plotly-binding-4.10.0/plotly.js"></script>
<script src="site_libs/typedarray-0.1/typedarray.min.js"></script>
<link href="site_libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="site_libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>
<link href="site_libs/plotly-htmlwidgets-css-2.5.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="site_libs/plotly-main-2.5.1/plotly-latest.min.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Overview</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Data Exploration
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="worldwide.html">Happiness Worldwide</a>
    </li>
    <li>
      <a href="Happiness_factors.html">Related factors</a>
    </li>
    <li>
      <a href="COVID19.html">Influnce of COVID19</a>
    </li>
  </ul>
</li>
<li>
  <a href="regression_analysis.html">Data Analysis</a>
</li>
<li>
  <a href="https://yirugong.shinyapps.io/shiny/">Map</a>
</li>
<li>
  <a href="data.html">Data</a>
</li>
<li>
  <a href="Proposal.html">Proposal</a>
</li>
<li>
  <a href="report.html">Report</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="mailto:&lt;xs2447@cumc.columbia.edu&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/YiruGONG/world_happiness_report.github.io">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">COVID19</h1>

</div>


<div id="data-input" class="section level2">
<h2>Data Input</h2>
<pre class="r"><code>covid_df = readxl::read_xlsx(&#39;MortalityDataWHR2021C2.xlsx&#39;) %&gt;% 
  drop_na() %&gt;% 
  janitor::clean_names() %&gt;% 
  mutate(
    death_change = all_cause_death_count_2020 - all_cause_death_count_2019) 

covid_longer = covid_df %&gt;% 
  pivot_longer(
    all_cause_death_count_2017:all_cause_death_count_2017,
    names_to = &quot;year&quot;,
    names_prefix = &quot;all_cause_death_count_&quot;,
    values_to = &quot;death&quot;
  ) %&gt;% 
  mutate(year = as.numeric(year))

happy_df = readxl::read_xls(&#39;DataPanelWHR2021C2.xls&#39;) %&gt;% 
  janitor::clean_names() %&gt;% 
  select(1:3) %&gt;% 
  subset(
    country_name != &quot;Kosovo&quot; &amp; country_name != &quot;Somaliland region&quot;
  ) %&gt;% 
  mutate(
    country_code = countrycode(country_name, &quot;country.name&quot;, &quot;iso3c&quot;)
  ) %&gt;% 
  relocate(country_code) %&gt;% 
  mutate(
    country_continent = countrycode(country_name, &quot;country.name&quot;, &quot;continent&quot;)
  ) %&gt;% 
  relocate(country_continent) %&gt;% 
  subset(year %in% c(2017,2018,2019,2020))

happy_df %&gt;% 
  group_by(country_continent) %&gt;% 
<<<<<<< HEAD
  summarize(n = n()) %&gt;% 
  knitr::kable(col.names = c(&quot;Continent&quot;, &quot;Number of Countries in Happiness Dataset&quot;))</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Continent</th>
<th align="right">Number of Countries in Happiness Dataset</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Africa</td>
<td align="right">138</td>
</tr>
<tr class="even">
<td align="left">Americas</td>
<td align="right">77</td>
</tr>
<tr class="odd">
<td align="left">Asia</td>
<td align="right">150</td>
</tr>
<tr class="even">
<td align="left">Europe</td>
<td align="right">151</td>
</tr>
<tr class="odd">
<td align="left">Oceania</td>
<td align="right">8</td>
</tr>
</tbody>
</table>
=======
  summarize(n = n())</code></pre>
<pre><code>## # A tibble: 5 x 2
##   country_continent     n
##   &lt;chr&gt;             &lt;int&gt;
## 1 Africa              138
## 2 Americas             77
## 3 Asia                150
## 4 Europe              151
## 5 Oceania               8</code></pre>
<pre class="r"><code>covid_death_rate = covid_df %&gt;% 
  plot_ly(x = ~country_name, 
         y = ~covid_19_deaths_per_100_000_population_in_2020,
         type = &quot;bar&quot;, colors = &quot;viridis&quot;)

covid_death_rate</code></pre>
<div id="htmlwidget-442e018c0a0645354e17" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-442e018c0a0645354e17">{"x":{"visdat":{"3f0ce8a7340":["function () ","plotlyVisDat"]},"cur_data":"3f0ce8a7340","attrs":{"3f0ce8a7340":{"x":{},"y":{},"colors":"viridis","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"xaxis":{"domain":[0,1],"automargin":true,"title":"country_name","type":"category","categoryorder":"array","categoryarray":["Armenia","Austria","Azerbaijan","Belgium","Brazil","Bulgaria","Chile","Colombia","Croatia","Cyprus","Czech Republic","Denmark","Ecuador","Estonia","Finland","France","Germany","Greece","Hong Kong S.A.R. of China","Hungary","Iceland","Israel","Italy","Japan","Kazakhstan","Kosovo","Kyrgyzstan","Latvia","Lithuania","Luxembourg","Malaysia","Malta","Mauritius","Mexico","Moldova","Mongolia","Netherlands","New Zealand","North Macedonia","Norway","Oman","Panama","Paraguay","Peru","Poland","Portugal","Qatar","Russia","Serbia","Singapore","Slovakia","Slovenia","South Korea","Spain","Sweden","Switzerland","Taiwan Province of China","Tajikistan","Thailand","Ukraine","United Kingdom","United States","Uzbekistan"]},"yaxis":{"domain":[0,1],"automargin":true,"title":"covid_19_deaths_per_100_000_population_in_2020"},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["United States","United Kingdom","France","Germany","Netherlands","Belgium","Spain","Italy","Poland","Hungary","Czech Republic","Sweden","Greece","Denmark","Hong Kong S.A.R. of China","Singapore","Japan","Brazil","Mexico","Israel","Thailand","New Zealand","South Korea","Taiwan Province of China","Kazakhstan","Kyrgyzstan","Moldova","Russia","Ukraine","Armenia","Austria","Azerbaijan","Bulgaria","Chile","Colombia","Croatia","Cyprus","Ecuador","Estonia","Finland","Iceland","Latvia","Lithuania","Luxembourg","North Macedonia","Malaysia","Malta","Mauritius","Mongolia","Norway","Oman","Panama","Paraguay","Peru","Portugal","Qatar","Serbia","Slovakia","Slovenia","Switzerland","Tajikistan","Uzbekistan","Kosovo"],"y":[104.451400756836,108.449501037598,99.211799621582,40.3311004638672,67.260498046875,168.495697021484,108.731101989746,122.654197692871,75.4467010498047,98.7230987548828,108.133499145508,86.4122009277344,46.4162979125977,22.4093990325928,1.97412610054016,0.495699971914291,2.60290002822876,91.7151031494141,97.5756988525391,38.4146995544434,0.0903000012040138,0.518400013446808,1.78859996795654,0.0294000003486872,14.7044010162354,20.7688999176025,73.996696472168,38.5591011047363,44.0872001647949,95.2675018310547,69.0841979980469,26.0475006103516,109.031600952148,86.8791961669922,84.926399230957,95.4870986938477,13.5860004425049,79.5439987182617,17.2630004882812,10.125,8.49820041656494,33.6655006408691,53.5578002929688,79.0764999389648,120.141296386719,1.45519995689392,49.5992012023926,0.786300003528595,0.0305000003427267,8.04240036010742,29.3540000915527,93.2146987915039,31.7139015197754,114.279296875,67.7276992797852,8.50380039215088,47.1886978149414,39.1601028442383,129.730102539062,88.3343048095703,0.943599998950958,1.83449995517731,68.9164962768555],"type":"bar","marker":{"color":"rgba(31,119,180,1)","line":{"color":"rgba(31,119,180,1)"}},"error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
>>>>>>> 2a850f6f9b539c95f0f865f30c478e12bdf1881d
<pre class="r"><code>happy_wider = 
  happy_df %&gt;% 
  pivot_wider(
    names_from = year,
    values_from = life_ladder,
    names_glue = &quot;life_ladder_{year}&quot;
  ) %&gt;% 
  mutate(happy_change_2020 = life_ladder_2020 - life_ladder_2019,
         happy_change_2019 = life_ladder_2019 - life_ladder_2018) %&gt;% 
  mutate(change_in_speed = happy_change_2020 - happy_change_2019)

covid_happy_trend = 
  left_join(covid_df, happy_wider, by = &quot;country_name&quot;) %&gt;% 
  drop_na()</code></pre>
</div>
<div id="covid19-distributions" class="section level2">
<h2>COVID19 Distributions</h2>
<pre class="r"><code>covid_death_rate = covid_happy_trend %&gt;% 
  plot_ly(x = ~country_name, 
         y = ~covid_19_deaths_per_100_000_population_in_2020,
         type = &quot;bar&quot;, color = ~country_continent) %&gt;% 
  layout(
    title = &quot;COVID19 Deaths per 100,000 Population in 2020 in Each Country&quot;,
    xaxis = list(title = &#39;Country Name&#39;),
    yaxis = list(title = &#39;COVID19 Deaths per 100,000 Population&#39;))

covid_death_rate</code></pre>
<div id="htmlwidget-c1064f39441f50b56943" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-c1064f39441f50b56943">{"x":{"visdat":{"e3ed30e79928":["function () ","plotlyVisDat"]},"cur_data":"e3ed30e79928","attrs":{"e3ed30e79928":{"x":{},"y":{},"color":{},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"COVID19 Deaths per 100,000 Population in 2020 in Each Country","xaxis":{"domain":[0,1],"automargin":true,"title":"Country Name","type":"category","categoryorder":"array","categoryarray":["Austria","Belgium","Brazil","Bulgaria","Chile","Colombia","Croatia","Cyprus","Denmark","Ecuador","Estonia","Finland","France","Germany","Greece","Hungary","Israel","Italy","Japan","Kazakhstan","Kyrgyzstan","Latvia","Lithuania","Malta","Mauritius","Mexico","Moldova","Mongolia","Netherlands","New Zealand","North Macedonia","Norway","Poland","Portugal","Russia","Serbia","Slovakia","Slovenia","South Korea","Spain","Sweden","Switzerland","Taiwan Province of China","Tajikistan","Thailand","Ukraine","United Kingdom","United States"]},"yaxis":{"domain":[0,1],"automargin":true,"title":"COVID19 Deaths per 100,000 Population"},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["Mauritius"],"y":[0.786300003528595],"type":"bar","name":"Africa","marker":{"color":"rgba(102,194,165,1)","line":{"color":"rgba(102,194,165,1)"}},"textfont":{"color":"rgba(102,194,165,1)"},"error_y":{"color":"rgba(102,194,165,1)"},"error_x":{"color":"rgba(102,194,165,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["United States","Brazil","Mexico","Chile","Colombia","Ecuador"],"y":[104.451400756836,91.7151031494141,97.5756988525391,86.8791961669922,84.926399230957,79.5439987182617],"type":"bar","name":"Americas","marker":{"color":"rgba(252,141,98,1)","line":{"color":"rgba(252,141,98,1)"}},"textfont":{"color":"rgba(252,141,98,1)"},"error_y":{"color":"rgba(252,141,98,1)"},"error_x":{"color":"rgba(252,141,98,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Japan","Israel","Thailand","South Korea","Taiwan Province of China","Kazakhstan","Kyrgyzstan","Cyprus","Mongolia","Tajikistan"],"y":[2.60290002822876,38.4146995544434,0.0903000012040138,1.78859996795654,0.0294000003486872,14.7044010162354,20.7688999176025,13.5860004425049,0.0305000003427267,0.943599998950958],"type":"bar","name":"Asia","marker":{"color":"rgba(141,160,203,1)","line":{"color":"rgba(141,160,203,1)"}},"textfont":{"color":"rgba(141,160,203,1)"},"error_y":{"color":"rgba(141,160,203,1)"},"error_x":{"color":"rgba(141,160,203,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["United Kingdom","France","Germany","Netherlands","Belgium","Spain","Italy","Poland","Hungary","Sweden","Greece","Denmark","Moldova","Russia","Ukraine","Austria","Bulgaria","Croatia","Estonia","Finland","Latvia","Lithuania","North Macedonia","Malta","Norway","Portugal","Serbia","Slovakia","Slovenia","Switzerland"],"y":[108.449501037598,99.211799621582,40.3311004638672,67.260498046875,168.495697021484,108.731101989746,122.654197692871,75.4467010498047,98.7230987548828,86.4122009277344,46.4162979125977,22.4093990325928,73.996696472168,38.5591011047363,44.0872001647949,69.0841979980469,109.031600952148,95.4870986938477,17.2630004882812,10.125,33.6655006408691,53.5578002929688,120.141296386719,49.5992012023926,8.04240036010742,67.7276992797852,47.1886978149414,39.1601028442383,129.730102539062,88.3343048095703],"type":"bar","name":"Europe","marker":{"color":"rgba(231,138,195,1)","line":{"color":"rgba(231,138,195,1)"}},"textfont":{"color":"rgba(231,138,195,1)"},"error_y":{"color":"rgba(231,138,195,1)"},"error_x":{"color":"rgba(231,138,195,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["New Zealand"],"y":[0.518400013446808],"type":"bar","name":"Oceania","marker":{"color":"rgba(166,216,84,1)","line":{"color":"rgba(166,216,84,1)"}},"textfont":{"color":"rgba(166,216,84,1)"},"error_y":{"color":"rgba(166,216,84,1)"},"error_x":{"color":"rgba(166,216,84,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<pre class="r"><code>covid_happy_trend %&gt;% 
  group_by(country_continent) %&gt;% 
<<<<<<< HEAD
  summarize(n = n()) %&gt;% 
  knitr::kable(col.names = c(&quot;Continent&quot;, &quot;Number of Countries in both Happiness and COVID Dataset&quot;))</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Continent</th>
<th align="right">Number of Countries in both Happiness and COVID Dataset</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Africa</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">Americas</td>
<td align="right">6</td>
</tr>
<tr class="odd">
<td align="left">Asia</td>
<td align="right">10</td>
</tr>
<tr class="even">
<td align="left">Europe</td>
<td align="right">30</td>
</tr>
<tr class="odd">
<td align="left">Oceania</td>
<td align="right">1</td>
</tr>
</tbody>
</table>
</div>
<div id="change-in-happiness-score-related-to-covid19" class="section level2">
<h2>Change in Happiness Score Related to COVID19</h2>
=======
  summarise(n = n())</code></pre>
<pre><code>## # A tibble: 6 x 2
##   country_continent     n
##   &lt;chr&gt;             &lt;int&gt;
## 1 Africa                1
## 2 Americas              9
## 3 Asia                 16
## 4 Europe               33
## 5 Oceania               1
## 6 &lt;NA&gt;                  3</code></pre>
>>>>>>> 2a850f6f9b539c95f0f865f30c478e12bdf1881d
<pre class="r"><code>covid_happy_trend %&gt;% 
  ggplot(aes(x = covid_19_deaths_per_100_000_population_in_2020, 
             y = happy_change_2020)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;) + 
  ggtitle(&quot;Plot of Relationship between COVID19 Deaths Rate and Increasees in Happiness Scores with Linear Regression Model&quot;) + 
  xlab(&quot;COVID19 Deaths per 100,000 Population in 2020&quot;) +
  ylab(&quot;Increase in Happiness Score from 2019 to 2020&quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="COVID19_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>covid_happy_trend_fc = 
  covid_happy_trend %&gt;% 
  mutate(country_continent = factor(country_continent))

model = lm(happy_change_2020 ~ covid_19_deaths_per_100_000_population_in_2020, data = covid_happy_trend_fc)
summary(model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = happy_change_2020 ~ covid_19_deaths_per_100_000_population_in_2020, 
##     data = covid_happy_trend_fc)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.63023 -0.19340  0.01847  0.14833  0.90294 
## 
## Coefficients:
##                                                  Estimate Std. Error t value
## (Intercept)                                     0.0679156  0.0741398   0.916
## covid_19_deaths_per_100_000_population_in_2020 -0.0009279  0.0010276  -0.903
##                                                Pr(&gt;|t|)
## (Intercept)                                       0.364
## covid_19_deaths_per_100_000_population_in_2020    0.371
## 
## Residual standard error: 0.3066 on 46 degrees of freedom
## Multiple R-squared:  0.01742,    Adjusted R-squared:  -0.003944 
## F-statistic: 0.8153 on 1 and 46 DF,  p-value: 0.3712</code></pre>
<p>We expected that COVID19 will decrease the happiness score. However, even though the regression has a negative slope, there is no significant relationship between covid-related death and happiness score. This may result from the lack of data. In our happiness dataframe, there are 166 countries. However, there are only 60 countries have both COVID data and happiness score. This mean only 36% of the total countries we are interested in have COVID data. Among the countries have data related to COVID, 33 countries are from Europe, which covers 55% of the dataframe. In details we have 33 out of 151 European countries (21.85%), 16 out of 150 Asian countries (10.67%), 9 out of 77 American countries (11.69%), 1 out of 138 African countries (0.72%) and 1 from 9 Oceanian countries (11.11%). Number of European countries is un-proportionally high compared to the country numbers in other continent. On the other hand, the number of African countries is the lowest. The disproportion could bring more developed countries than developing countries to our dataset because Europe is concentrated with developed countries while Africa is concentrated with developing countries. Therefore, the dataset we have may significant biased because developed countries may be more stable to epidemic impact. So the data we have right now cannot give accurate relationship result.</p>
<pre class="r"><code>model = lm(happy_change_2020 ~ covid_19_deaths_per_100_000_population_in_2020 + country_continent, data = covid_happy_trend_fc)
summary(model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = happy_change_2020 ~ covid_19_deaths_per_100_000_population_in_2020 + 
##     country_continent, data = covid_happy_trend_fc)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.63111 -0.21188 -0.00395  0.13530  0.83869 
## 
## Coefficients:
##                                                  Estimate Std. Error t value
## (Intercept)                                    -0.2256695  0.2987959  -0.755
## covid_19_deaths_per_100_000_population_in_2020 -0.0002485  0.0013796  -0.180
## country_continentAmericas                      -0.0204513  0.3458256  -0.059
## country_continentAsia                           0.3260302  0.3135975   1.040
## country_continentEurope                         0.2929524  0.3189358   0.919
## country_continentOceania                        0.2780058  0.4225585   0.658
##                                                Pr(&gt;|t|)
## (Intercept)                                       0.454
## covid_19_deaths_per_100_000_population_in_2020    0.858
## country_continentAmericas                         0.953
## country_continentAsia                             0.304
## country_continentEurope                           0.364
## country_continentOceania                          0.514
## 
## Residual standard error: 0.2988 on 42 degrees of freedom
## Multiple R-squared:  0.1477, Adjusted R-squared:  0.04627 
## F-statistic: 1.456 on 5 and 42 DF,  p-value: 0.2246</code></pre>
<p>After adding the continent variables, there is still no significant relationship. However, from the limit information, we can see that Americas are more likely to be effected by COVID19 because of the negatively relationship.</p>
</div>
<div id="change-in-happiness-score-increase-speed-related-to-covid19" class="section level2">
<h2>Change in Happiness Score Increase Speed Related to COVID19</h2>
<pre class="r"><code>covid_happy_trend %&gt;% 
  plot_ly(x = ~country_name, 
         y = ~change_in_speed,
         type = &quot;bar&quot;, color = ~country_continent) %&gt;% 
  layout(
    title = &quot;Change in the Happiness Score Rise Rate&quot;,
    xaxis = list(title = &#39;Country Name&#39;),
    yaxis = list(title = &#39;Difference between Increase of Happiness Score \nin 2020 and Increase of Happiness Score in 2019&#39;))</code></pre>
<div id="htmlwidget-a8ac8690128f5e72370b" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-a8ac8690128f5e72370b">{"x":{"visdat":{"e3ed6f00ff32":["function () ","plotlyVisDat"]},"cur_data":"e3ed6f00ff32","attrs":{"e3ed6f00ff32":{"x":{},"y":{},"color":{},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Change in the Happiness Score Rise Rate","xaxis":{"domain":[0,1],"automargin":true,"title":"Country Name","type":"category","categoryorder":"array","categoryarray":["Austria","Belgium","Brazil","Bulgaria","Chile","Colombia","Croatia","Cyprus","Denmark","Ecuador","Estonia","Finland","France","Germany","Greece","Hungary","Israel","Italy","Japan","Kazakhstan","Kyrgyzstan","Latvia","Lithuania","Malta","Mauritius","Mexico","Moldova","Mongolia","Netherlands","New Zealand","North Macedonia","Norway","Poland","Portugal","Russia","Serbia","Slovakia","Slovenia","South Korea","Spain","Sweden","Switzerland","Taiwan Province of China","Tajikistan","Thailand","Ukraine","United Kingdom","United States"]},"yaxis":{"domain":[0,1],"automargin":true,"title":"Difference between Increase of Happiness Score <br />in 2020 and Increase of Happiness Score in 2019"},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["Mauritius"],"y":[-0.585289478302002],"type":"bar","name":"Africa","marker":{"color":"rgba(102,194,165,1)","line":{"color":"rgba(102,194,165,1)"}},"textfont":{"color":"rgba(102,194,165,1)"},"error_y":{"color":"rgba(102,194,165,1)"},"error_x":{"color":"rgba(102,194,165,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["United States","Brazil","Mexico","Chile","Colombia","Ecuador"],"y":[0.0233702659606934,-0.601658344268799,-0.350090980529785,0.702363014221191,-1.0079083442688,-0.135790348052979],"type":"bar","name":"Americas","marker":{"color":"rgba(252,141,98,1)","line":{"color":"rgba(252,141,98,1)"}},"textfont":{"color":"rgba(252,141,98,1)"},"error_y":{"color":"rgba(252,141,98,1)"},"error_x":{"color":"rgba(252,141,98,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Japan","Israel","Thailand","South Korea","Taiwan Province of China","Kazakhstan","Kyrgyzstan","Cyprus","Mongolia","Tajikistan"],"y":[0.0954604148864746,-0.541452884674072,-0.148196697235107,-0.172706604003906,0.143892765045166,-0.368631362915039,0.176527976989746,0.262588024139404,0.35017728805542,-0.0571632385253906],"type":"bar","name":"Asia","marker":{"color":"rgba(141,160,203,1)","line":{"color":"rgba(141,160,203,1)"}},"textfont":{"color":"rgba(141,160,203,1)"},"error_y":{"color":"rgba(141,160,203,1)"},"error_x":{"color":"rgba(141,160,203,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["United Kingdom","France","Germany","Netherlands","Belgium","Spain","Italy","Poland","Hungary","Sweden","Greece","Denmark","Moldova","Russia","Ukraine","Austria","Bulgaria","Croatia","Estonia","Finland","Latvia","Lithuania","North Macedonia","Malta","Norway","Portugal","Serbia","Slovakia","Slovenia","Switzerland"],"y":[-0.282680034637451,0.000726699829101562,0.359317302703857,0.117007732391357,0.186656475067139,0.100647449493408,0.114048957824707,-0.233247756958008,-0.0266990661621094,-0.107052326202393,-0.707409858703613,-0.222589492797852,-0.112995147705078,0.127741813659668,0.528060436248779,0.21876859664917,0.479660511016846,0.792775630950928,0.474583625793457,0.186761379241943,0.19065523147583,0.572062015533447,0.262528419494629,-0.399421215057373,-0.149984836578369,-0.503331661224365,-0.504775047302246,0.267351627349854,-0.619051933288574,-0.371419906616211],"type":"bar","name":"Europe","marker":{"color":"rgba(231,138,195,1)","line":{"color":"rgba(231,138,195,1)"}},"textfont":{"color":"rgba(231,138,195,1)"},"error_y":{"color":"rgba(231,138,195,1)"},"error_x":{"color":"rgba(231,138,195,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["New Zealand"],"y":[0.217319011688232],"type":"bar","name":"Oceania","marker":{"color":"rgba(166,216,84,1)","line":{"color":"rgba(166,216,84,1)"}},"textfont":{"color":"rgba(166,216,84,1)"},"error_y":{"color":"rgba(166,216,84,1)"},"error_x":{"color":"rgba(166,216,84,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<pre class="r"><code>model = lm(change_in_speed ~ covid_19_deaths_per_100_000_population_in_2020 + country_continent, data = covid_happy_trend_fc)
summary(model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = change_in_speed ~ covid_19_deaths_per_100_000_population_in_2020 + 
##     country_continent, data = covid_happy_trend_fc)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.78294 -0.26032  0.04238  0.21856  0.92842 
## 
## Coefficients:
##                                                  Estimate Std. Error t value
## (Intercept)                                    -0.5848488  0.3929198  -1.488
## covid_19_deaths_per_100_000_population_in_2020 -0.0005605  0.0018142  -0.309
## country_continentAmericas                       0.4074841  0.4547644   0.896
## country_continentAsia                           0.5641087  0.4123841   1.368
## country_continentEurope                         0.6494420  0.4194040   1.548
## country_continentOceania                        0.8024583  0.5556691   1.444
##                                                Pr(&gt;|t|)
## (Intercept)                                       0.144
## covid_19_deaths_per_100_000_population_in_2020    0.759
## country_continentAmericas                         0.375
## country_continentAsia                             0.179
## country_continentEurope                           0.129
## country_continentOceania                          0.156
## 
## Residual standard error: 0.3929 on 42 degrees of freedom
## Multiple R-squared:  0.09858,    Adjusted R-squared:  -0.008727 
## F-statistic: 0.9187 on 5 and 42 DF,  p-value: 0.4784</code></pre>
<p>From the fitted model, we see that European and Oceania slopes of change in happiness speed are high. This means that in European and Oceania countries, the happiness scores are increasing quicker than other countries. This may help to explain why the COVID data concentrated in Europe countries are not representative: since European and Oceania countries’ happiness scores are increasing at a high rate, even if COVID19 has negative effect on the happiness score, it does not be reflected as a decrease in happiness score.</p>
</div>
<div id="change-in-death-related-to-covid19" class="section level2">
<h2>Change in Death Related to COVID19</h2>
<pre class="r"><code>covid_happy_trend %&gt;% 
  ggplot(aes(x = covid_19_deaths_per_100_000_population_in_2020, 
             y = death_change)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;) +
  ggtitle(&quot;Plot of Relationship between COVID19 Deaths Rate and Total Death in 2020&quot;) + 
  xlab(&quot;COVID19 Deaths per 100,000 Population in 2020&quot;) +
  ylab(&quot;Total Death in 2020&quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="COVID19_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre class="r"><code>model = lm(death_change ~ covid_19_deaths_per_100_000_population_in_2020, data = covid_happy_trend_fc)
summary(model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = death_change ~ covid_19_deaths_per_100_000_population_in_2020, 
##     data = covid_happy_trend_fc)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -109594  -41445  -16015   -1543  489605 
## 
## Coefficients:
##                                                Estimate Std. Error t value
## (Intercept)                                      5228.7    24608.7   0.212
## covid_19_deaths_per_100_000_population_in_2020    741.2      341.1   2.173
##                                                Pr(&gt;|t|)  
## (Intercept)                                       0.833  
## covid_19_deaths_per_100_000_population_in_2020    0.035 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 101800 on 46 degrees of freedom
## Multiple R-squared:  0.09309,    Adjusted R-squared:  0.07337 
## F-statistic: 4.721 on 1 and 46 DF,  p-value: 0.03497</code></pre>
<p>Covid-related deaths contribute to the total death as the slope 741.2 is positive. Based on that information, we also want to consider survivorship bias in the data. Since our data about happiness score is based on survey, people who were infected by COVID19 may had no access to the survey because they were hosptialized or dead. Therefore, the data we have may not have ability to reflect COVID19’s influence. This may explain why some European countries have high death rate related to COVID19 but still have positive changes in happiness scores.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
